linters-settings:
  revive:
    disable:
      - exported

linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
  disable:
    - unused

run:
  deadline: 5m

issues:
  exclude-use-default: false
